# Generated by Django 4.2.3 on 2023-08-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'female')], max_length=10)),
                ('birth_date', models.DateField()),
                ('inscription_number', models.PositiveIntegerField()),
                ('inscription_date', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculty'),
        ),
        migrations.CreateModel(
            name='BedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('M', 'Male'), ('F', 'female')], max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateField(auto_now_add=True)),
                ('bedroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bedroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_letter', models.TextField(max_length=500)),
                ('date_application', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'gender', 'birth_date', 'faculty', 'department', 'inscription_date', 'inscription_number'), name='unique_student'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('designation', 'faculty_name'), name='unique_department'),
        ),
        migrations.AddConstraint(
            model_name='bedroom',
            constraint=models.UniqueConstraint(fields=('number', 'category', 'status', 'location'), name='unique_bedroom'),
        ),
        migrations.AddConstraint(
            model_name='attribution',
            constraint=models.UniqueConstraint(fields=('student', 'bedroom', 'date_attribution'), name='unique_attribution'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'application_letter', 'date_application'), name='unique_bedroom_application'),
        ),
    ]
