# Generated by Django 4.2.3 on 2023-12-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepter'), ('rejected', 'Rejeter'), ('pending', 'En attente'), ('not_applied', 'Pas encore appliqué')], default='not_applied', max_length=20),
        ),
    ]
