# Generated by Django 4.2.3 on 2023-08-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_attribution_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='accommodation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.accommodation'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='bedroom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.bedroom'),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.application'),
        ),
    ]
