# Generated by Django 4.2.3 on 2023-08-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_application_accommodation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attribution',
            name='unique_attribution',
        ),
    ]
