# Generated by Django 4.2.3 on 2023-12-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[(1, 'Accepter'), (0, 'Rejeter'), (2, 'En attente'), (3, 'Pas encore appliqué')], default=3, max_length=20),
        ),
    ]
