# Generated by Django 4.2.3 on 2023-12-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[(1, 'Accepter'), (0, 'Rejeter'), (2, 'En attente')], default=2, max_length=20),
        ),
    ]
