# Generated by Django 4.2.3 on 2023-08-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_application_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='accommodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.accommodation'),
        ),
    ]
