# Generated by Django 4.2.3 on 2023-12-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_bedroom_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(1, 'Accepter'), (0, 'Rejeter'), (2, 'En attente')], default=2, max_length=20),
        ),
    ]
