# Generated by Django 4.2.3 on 2023-12-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_application_unique_bedroom_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(1, 'Accepter'), (0, 'Rejeter'), (2, 'En attente')], default=2),
        ),
    ]
