# Generated by Django 4.2.3 on 2023-12-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_application_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_bedroom_application',
        ),
        migrations.RemoveConstraint(
            model_name='bedroom',
            name='unique_bedroom',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department',
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_student',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='bedroom',
            new_name='chambre',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='date_application',
            new_name='date_de_demande',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='entry_date',
            new_name='date_entree',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='student',
            new_name='etudiant',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='location',
            new_name='localisation',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='accommodation',
            new_name='logement',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='residence_card_maquisard',
            new_name='maquisard_carte_de_residence',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='residence_card_number',
            new_name='numero_carte_de_residence',
        ),
        migrations.RenameField(
            model_name='bedroom',
            old_name='category',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='bedroom',
            old_name='location',
            new_name='localisation',
        ),
        migrations.RenameField(
            model_name='bedroom',
            old_name='number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='faculty_name',
            new_name='nom_de_la_faculte',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='birth_date',
            new_name='date_de_naissance',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='inscription_date',
            new_name='date_inscription',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='departement',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='faculty',
            new_name='faculte',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='inscription_number',
            new_name='numero_inscription',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='prenom',
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('matricule', 'etudiant', 'status'), name='unique_chambre_application'),
        ),
        migrations.AddConstraint(
            model_name='bedroom',
            constraint=models.UniqueConstraint(fields=('numero', 'categorie', 'status', 'localisation'), name='unique_bedroom'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('designation', 'nom_de_la_faculte'), name='unique_department'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('prenom', 'nom', 'genre', 'date_de_naissance', 'faculte', 'departement', 'date_inscription', 'numero_inscription'), name='unique_student'),
        ),
    ]
