# Generated by Django 4.2.3 on 2023-12-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_application_unique_bedroom_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='faculty',
            new_name='faculte',
        ),
    ]
