from .faculty import *
from .campus import *
from .accommodation import *
from .location import *
from .department import *
from .bedroom import *
from .student import *
from .application import *
from .attribution import *
